---
- name: VoIP configuration
  hosts: all
  connection: local
  gather_facts: no
  vars:
      conf_dir: "{{ playbook_dir }}/compiled/"
      creds:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"

  pre_tasks:
     - name: Set some global facts
       set_fact:
          host_dir: "{{ conf_dir}}/{{ inventory_hostname}}"
       changed_when: False
     - name: Make sure there are no remains from a previous run
       file:
         path: "{{ host_dir }}/voip.conf"
         state: absent
       changed_when: False

     - name: Create folder to store configurations and diffs for/from the devices
       file:
         path: "{{ host_dir }}"
         state: directory
       changed_when: False

     - name: Get node type
       set_fact:
         node_type: "{{ inventory_hostname.split('-')[0] }}"

     - name: Get my node ID
       set_fact:
         id: "{{ inventory_hostname.split('-')[1] }}"

- name: VoIP Configuration
  hosts: all
  connection: local
  vars:
      creds:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
  roles:
    - voip
    - remove_voip

  post_tasks:
  - name: Set state to enable deployment by default
    set_fact:
      state: "enabled"
  - name: Load config_file
    ios_config:
      src: "{{ host_dir }}/voip.conf"
      provider: "{{creds}}"
    when: state == "enabled"

  - name: Remove Voip
    ios_config:
      src: "{{ host_dir }}/remove_voip.conf"
      provider: "{{creds}}"
    when: state == "disabled"
