---
- hosts: all
  name: Create and read node data model
  vars:
    validations_dir: "validations"
  tasks:
  - name: Create folder to validation model
    file:
      path: "{{ validations_dir }}"
      state: directory
    changed_when: False

  - name: Get my node ID
    set_fact:
      id: "{{ inventory_hostname.split('-')[1] }}"

  - include_vars: "roles/fabric/vars/main.yml"

  - name: Create per-node data model from fabric data model
    template: src=fabric-to-nodes.j2 dest={{validations_dir}}/{{inventory_hostname}}_node.yml


- hosts: all
  name: Validate Fabric
  tasks:
  - include_vars: "validations/{{inventory_hostname}}_node.yml"
  - include_tasks: "includes/validate.yml"
