---
interfaces:
  - name: "Loopback0"
    description: "Loopback interface"
    ips:
      - "172.16.16.1/32"
    enabled: true

  - name: "E0/1"
    description: "Link1"
    ips:
      - "192.168.100.102/24"
    enabled: true

  - name: "e0/2"
    description: "Link2"
    ips:
      - "192.168.200.103/24"
    enabled: true


as: "65101"
neighbors:
  - name: R2
    ip: "192.168.100.201"
    asn: "65102"
  - name: R3
    ip: "192.168.200.31"
    asn: "65103"
